import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/modules/layout/templates/header/index"
import NavMobile from "@/modules/layout/templates/header/index-mobile"
import Footer from "@/modules/layout/templates/footer/index";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import FooterImage from "@/modules/layout/templates/footer-image";
config.autoAddCss = false;
// import { MyProvider } from './context';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const geistChilanka = localFont({
  src: "./fonts/Chilanka-Regular.woff",
  variable: "--font-geist-chilanka",
  weight: "100 900",
});

const geistMontserrat = localFont({
  src: "./fonts/Montserrat-Black.woff",
  variable: "--font-geist-montserrat",
  // weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistChilanka.variable}  ${geistMontserrat.variable} antialiased`}
      >
        <Nav></Nav>
        <NavMobile></NavMobile>
        {children}
        <FooterImage></FooterImage>
        <Footer></Footer>
      </body>
    </html>
  );
}
